name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: actions-setup-redis
      uses: shogo82148/actions-setup-redis@v1.25.1
    - uses: actions/checkout@v2
    - name: setup clojure
      uses: DeLaGuardo/setup-clojure@master
      with:
        tools-deps: '1.10.1.763'
    - name: run ripley unit tests
      run: clojure -A:dev:test
    - uses: actions/checkout@v2
      with:
        repository: tatut/cypress-example-todomvc
        path: cypress-todomvc
    - name: run todomvc cypress tests
      run: bash examples/todomvc/cypress.sh
